### ISSUE TITLE
Not working with electron 7.0.0 above

### ISSUE THREAD

**Issue by aswzen** [praharshjain/Electron-PDF-Viewer#5]
Hi there, 

this example seems not working with electron 7.0.0 or above, after selecting the pdf file then nothing happened.

**Comment by praharshjain** [comment]
Hi,
The package.json file clearly has  "electron": "^4.1.4" in dependencies.

**Comment by Alex313031** [comment]
@aswzen @praharshjain I made an up to date version with Electron 22.x, context menus, and CSS tweaks here > https://github.com/Alex313031/electron-pdf-viewer

**Comment by praharshjain** [comment]
@aswzen @Alex313031 
Although, the current code is updated to work with Electron 23.x, I would recommend using https://github.com/praharshjain/Vudit-Desktop instead of this. Vudit is a successor of this project and it has support for opening many more file types than just PDF.
